#pragma once

// Persistent settings storage.
#define SETTINGS_ADDRESS_DEFAULT 0
#define SETTINGS_MAGIC_DEFAULT 0x44425331UL
#define SETTINGS_VERSION_DEFAULT 7
#define SETTINGS_SAVE_DELAY_MS_DEFAULT 2000
#define SETTINGS_CHECKSUM_SEED_DEFAULT 0xA55A

// Light strip hardware and defaults.
#define STRIP_PWM_MAX_DEFAULT 1023
#define STRIP_PWM_FREQUENCY_HZ_DEFAULT 2000
#define STRIP_BUTTON_DEBOUNCE_MS_DEFAULT 50
#define STRIP_ENABLED_DEFAULT 0
#define STRIP_MODE_DEFAULT 2
#define STRIP_BRIGHTNESS_DEFAULT 256
#define STRIP_BRIGHTNESS_MIN_DEFAULT 0
#define STRIP_BRIGHTNESS_MAX_DEFAULT STRIP_PWM_MAX_DEFAULT
#define STRIP_KELVIN_MIX_DEFAULT (STRIP_PWM_MAX_DEFAULT / 2)
#define STRIP_COLD_MIN_DEFAULT 0
#define STRIP_COLD_MAX_DEFAULT STRIP_PWM_MAX_DEFAULT
#define STRIP_HOT_MIN_DEFAULT 0
#define STRIP_HOT_MAX_DEFAULT STRIP_PWM_MAX_DEFAULT
#define STRIP_BUTTON_CLICK_MS_DEFAULT 600
#define STRIP_BUTTON_LONG_MS_DEFAULT 600
#define STRIP_BUTTON_REPEAT_MS_DEFAULT 40
#define STRIP_BRIGHTNESS_STEP_DEFAULT 32
#define STRIP_KELVIN_STEP_DEFAULT 32
#define STRIP_CAPACITIVE_BUTTON_COUNT_DEFAULT 4
#define STRIP_BUTTON_0_ACTION_DEFAULT 2
#define STRIP_BUTTON_1_ACTION_DEFAULT 3
#define STRIP_BUTTON_2_ACTION_DEFAULT 0
#define STRIP_BUTTON_3_ACTION_DEFAULT 0

// Editable ranges.
#define STRIP_BUTTON_CLICK_MS_MIN_DEFAULT 100
#define STRIP_BUTTON_CLICK_MS_MAX_DEFAULT 2000
#define STRIP_BUTTON_LONG_MS_MIN_DEFAULT 100
#define STRIP_BUTTON_LONG_MS_MAX_DEFAULT 3000
#define STRIP_BUTTON_REPEAT_MS_MIN_DEFAULT 10
#define STRIP_BUTTON_REPEAT_MS_MAX_DEFAULT 1000
#define STRIP_STEP_MIN_DEFAULT 1
#define STRIP_STEP_MAX_DEFAULT 256
#define DISPLAY_TIMEOUT_MS_MIN_DEFAULT 5000
#define DISPLAY_TIMEOUT_MS_MAX_DEFAULT 60000
#define DISPLAY_TIMEOUT_MS_STEP_DEFAULT 1000
#define SENSOR_SAMPLE_INTERVAL_MS_MIN_DEFAULT 1000
#define SENSOR_SAMPLE_INTERVAL_MS_MAX_DEFAULT 30000
#define SENSOR_SAMPLE_INTERVAL_MS_STEP_DEFAULT 200
#define SENSOR_SAMPLE_COUNT_MIN_DEFAULT 1
#define SENSOR_SAMPLE_COUNT_MAX_DEFAULT 10

// Display and UI defaults.
#define DISPLAY_TIMEOUT_MS_DEFAULT 15000
#define DISPLAY_BOOT_DURATION_MS_DEFAULT 1600
#define DISPLAY_BOOT_STATUS_MS_DEFAULT 170
#define DISPLAY_BOOT_FINISH_DELAY_MS_DEFAULT 150
#define DISPLAY_BOOT_FRAME_MS_DEFAULT 20
#define DISPLAY_INPUT_SENSOR_PAUSE_MS_DEFAULT 350
#define DISPLAY_HOME_REDRAW_INTERVAL_MS_DEFAULT 1000
#define DISPLAY_STATUS_REDRAW_INTERVAL_MS_DEFAULT 1000
#define DISPLAY_MENU_VISIBLE_ROWS_DEFAULT 5
#define HOME_BOX_BIG_DEFAULT 0
#define HOME_BOX_SMALL_DEFAULT 1
#define HOME_BOX_DATA1_DEFAULT 2
#define HOME_BOX_DATA2_DEFAULT 3
#define HOME_BOX_DATA3_DEFAULT 4
#define HOME_FIELD_MAX_DEFAULT 12

// Sensor sampling defaults.
#define SENSOR_SAMPLE_INTERVAL_MS_DEFAULT 5000
#define SENSOR_SAMPLE_COUNT_DEFAULT 1
#define SENSOR_CLIMATE_INTERVAL_MS_DEFAULT 1000
#define SENSOR_AIR_QUALITY_INTERVAL_MS_DEFAULT 1000
#define SENSOR_LIGHT_INTERVAL_MS_DEFAULT 1000
#define SENSOR_SHT_INTERVAL_MS_DEFAULT 2000
#define SENSOR_CO2_POLL_INTERVAL_MS_DEFAULT 1000
#define SENSOR_SLOT_COUNT_DEFAULT 5
#define SENSOR_ATTEMPT_SPACING_MS_MIN_DEFAULT 200
#define SENSOR_TEMP_MIN_C_DEFAULT -40.0f
#define SENSOR_TEMP_MAX_C_DEFAULT 125.0f
#define SENSOR_HUMIDITY_MIN_DEFAULT 0.0f
#define SENSOR_HUMIDITY_MAX_DEFAULT 100.0f

// I2C bus and external EEPROM.
#define I2C_CLOCK_HZ_DEFAULT 400000
#define I2C_SCAN_START_ADDRESS_DEFAULT 0x08
#define I2C_SCAN_END_ADDRESS_DEFAULT 0x77
#define EEPROM_I2C_ADDRESS_MIN_DEFAULT 0x50
#define EEPROM_I2C_ADDRESS_MAX_DEFAULT 0x57
#define EEPROM_SIZE_BYTES_DEFAULT 4096
#define EEPROM_ADDRESS_BYTES_DEFAULT 2
#define EEPROM_PAGE_SIZE_BYTES_DEFAULT 32
#define EEPROM_WRITE_TIME_MS_DEFAULT 5

// Input controls.
#define ENCODER_BUTTON_DEBOUNCE_US_DEFAULT 35000
#define ENCODER_POSITION_DIVIDER_DEFAULT 2

// NeoPixel notifications.
#define NOTIFICATION_PIXEL_BRIGHTNESS_DEFAULT 32
#define NOTIFICATION_MODE_DEFAULT 0
#define NOTIFICATION_MODE_COUNT_DEFAULT 4

// System indicator.
#define STATUS_LED_BLINK_INTERVAL_MS_DEFAULT 500

// Generic runtime defaults.
#define TEMPERATURE_UNIT_DEFAULT 0
#define HARDWARE_TASK_HEARTBEAT_MS_DEFAULT 1000
#define MCU_MONITOR_INTERVAL_MS_DEFAULT 1000
