#pragma once

// =============================================================================
// DeskBridge default settings
// =============================================================================
// This file is intentionally centralized: every configurable default should live
// here before it is copied into EEPROM by DeskSettings.
//
// Naming convention:
// - *_DEFAULT: initial value used on factory reset.
// - *_MIN_DEFAULT / *_MAX_DEFAULT: editable limits.
// - *_STEP_DEFAULT: encoder/menu increment.
//
// EEPROM compatibility rule:
// - Changing SETTINGS_VERSION_DEFAULT invalidates the saved EEPROM configuration.
// - During active development this is acceptable when the saved structure changes.
// - Once the options are stable, freeze the version and add migrations instead.

// -----------------------------------------------------------------------------
// EEPROM layout and save policy
// -----------------------------------------------------------------------------
#define SETTINGS_ADDRESS_DEFAULT 0
#define SETTINGS_MAGIC_DEFAULT 0x44425331UL
#define SETTINGS_VERSION_DEFAULT 11
#define SETTINGS_SAVE_DELAY_MS_DEFAULT 2000
#define SETTINGS_CHECKSUM_SEED_DEFAULT 0xA55A

// -----------------------------------------------------------------------------
// Light strip: runtime defaults
// -----------------------------------------------------------------------------
// Physical PWM is generated by CHIP_KEYPAD at 1.6 kHz / 16-bit.
// Mode encoding:
//   0 = OneSimple
//   1 = TwoSimple
//   2 = Composite WW/CW
#define STRIP_PWM_MAX_DEFAULT 65535
#define STRIP_ENABLED_DEFAULT 0
#define STRIP_MODE_DEFAULT 2
#define STRIP_BRIGHTNESS_DEFAULT 16384
#define STRIP_BRIGHTNESS_MIN_DEFAULT 0
#define STRIP_BRIGHTNESS_MAX_DEFAULT STRIP_PWM_MAX_DEFAULT
#define STRIP_KELVIN_MIX_DEFAULT (STRIP_PWM_MAX_DEFAULT / 2)
#define STRIP_COLD_MIN_DEFAULT 0
#define STRIP_COLD_MAX_DEFAULT STRIP_PWM_MAX_DEFAULT
#define STRIP_HOT_MIN_DEFAULT 0
#define STRIP_HOT_MAX_DEFAULT STRIP_PWM_MAX_DEFAULT

// Light strip: keypad timings and steps
#define STRIP_BUTTON_CLICK_MS_DEFAULT 600
#define STRIP_BUTTON_LONG_MS_DEFAULT 600
#define STRIP_BUTTON_REPEAT_MS_DEFAULT 40
#define STRIP_BRIGHTNESS_STEP_DEFAULT 2048
#define STRIP_KELVIN_STEP_DEFAULT 2048

// Light strip: editable limits
#define STRIP_BUTTON_CLICK_MS_MIN_DEFAULT 100
#define STRIP_BUTTON_CLICK_MS_MAX_DEFAULT 600
#define STRIP_BUTTON_LONG_MS_MIN_DEFAULT 800
#define STRIP_BUTTON_LONG_MS_MAX_DEFAULT 3200
#define STRIP_BUTTON_REPEAT_MS_MIN_DEFAULT 10
#define STRIP_BUTTON_REPEAT_MS_MAX_DEFAULT 1000
#define STRIP_STEP_MIN_DEFAULT 1
#define STRIP_STEP_MAX_DEFAULT 8192

// -----------------------------------------------------------------------------
// Display: timeout and active-window defaults
// -----------------------------------------------------------------------------
// Active mode encoding:
//   0 = AllTime
//   1 = ClockTime, using RTC minutes of day
//   2 = UsbMounted
#define DISPLAY_TIMEOUT_ENABLED_DEFAULT 1
#define DISPLAY_TIMEOUT_MS_DEFAULT 15000
#define DISPLAY_TIMEOUT_MS_MIN_DEFAULT 5000
#define DISPLAY_TIMEOUT_MS_MAX_DEFAULT 60000
#define DISPLAY_TIMEOUT_MS_STEP_DEFAULT 1000
#define DISPLAY_ACTIVE_MODE_ALL_TIME_DEFAULT 0
#define DISPLAY_ACTIVE_MODE_CLOCK_TIME_DEFAULT 1
#define DISPLAY_ACTIVE_MODE_USB_MOUNTED_DEFAULT 2
#define DISPLAY_ACTIVE_MODE_DEFAULT DISPLAY_ACTIVE_MODE_ALL_TIME_DEFAULT
#define DISPLAY_ACTIVE_START_MINUTE_DEFAULT 480
#define DISPLAY_ACTIVE_END_MINUTE_DEFAULT 1320
#define DISPLAY_ACTIVE_MINUTE_STEP_DEFAULT 15

// Display: HOME designs
//   0 = Classic, current mixed time/data layout
//   1 = Compact, time/date first with short data rows
//   2 = Data, sensor-first dashboard
#define DISPLAY_HOME_DESIGN_DEFAULT 0
#define DISPLAY_HOME_DESIGN_COUNT_DEFAULT 3

// Display: boot animation and refresh cadence
#define DISPLAY_BOOT_DURATION_MS_DEFAULT 1600
#define DISPLAY_BOOT_STATUS_MS_DEFAULT 170
#define DISPLAY_BOOT_FINISH_DELAY_MS_DEFAULT 150
#define DISPLAY_BOOT_FRAME_MS_DEFAULT 20
#define DISPLAY_INPUT_SENSOR_PAUSE_MS_DEFAULT 350
#define DISPLAY_HOME_REDRAW_INTERVAL_MS_DEFAULT 1000
#define DISPLAY_STATUS_REDRAW_INTERVAL_MS_DEFAULT 1000
#define DISPLAY_MENU_VISIBLE_ROWS_DEFAULT 5

// Display: HOME field mapping defaults
// Field encoding is defined by OledPanel::HomeField.
#define HOME_BOX_BIG_DEFAULT 0
#define HOME_BOX_SMALL_DEFAULT 1
#define HOME_BOX_DATA1_DEFAULT 2
#define HOME_BOX_DATA2_DEFAULT 3
#define HOME_BOX_DATA3_DEFAULT 4
#define HOME_FIELD_MAX_DEFAULT 12

// -----------------------------------------------------------------------------
// Sensor bus: sampling defaults
// -----------------------------------------------------------------------------
#define SENSOR_SAMPLE_INTERVAL_MS_DEFAULT 6000
#define SENSOR_SAMPLE_INTERVAL_MS_MIN_DEFAULT 1000
#define SENSOR_SAMPLE_INTERVAL_MS_MAX_DEFAULT 30000
#define SENSOR_SAMPLE_INTERVAL_MS_STEP_DEFAULT 200
#define SENSOR_SAMPLE_COUNT_DEFAULT 1
#define SENSOR_SAMPLE_COUNT_MIN_DEFAULT 1
#define SENSOR_SAMPLE_COUNT_MAX_DEFAULT 10

// Sensor bus: staggered measurement scheduler
#define SENSOR_CLIMATE_INTERVAL_MS_DEFAULT 1000
#define SENSOR_AIR_QUALITY_INTERVAL_MS_DEFAULT 1000
#define SENSOR_LIGHT_INTERVAL_MS_DEFAULT 1000
#define SENSOR_SHT_INTERVAL_MS_DEFAULT 2000
#define SENSOR_CO2_POLL_INTERVAL_MS_DEFAULT 1000
#define SENSOR_SLOT_COUNT_DEFAULT 5
#define SENSOR_ATTEMPT_SPACING_MS_MIN_DEFAULT 200

// Sensor bus: validity clamps
#define SENSOR_TEMP_MIN_C_DEFAULT -40.0f
#define SENSOR_TEMP_MAX_C_DEFAULT 125.0f
#define SENSOR_HUMIDITY_MIN_DEFAULT 0.0f
#define SENSOR_HUMIDITY_MAX_DEFAULT 100.0f

// -----------------------------------------------------------------------------
// I2C and EEPROM
// -----------------------------------------------------------------------------
// The firmware keeps System and Sensors as logical menus, but both currently
// share the physical PB9/PB8 I2C bus.
#define I2C_CLOCK_HZ_DEFAULT 100000
#define I2C_SCAN_START_ADDRESS_DEFAULT 0x08
#define I2C_SCAN_END_ADDRESS_DEFAULT 0x77
#define EEPROM_I2C_ADDRESS_MIN_DEFAULT 0x50
#define EEPROM_I2C_ADDRESS_MAX_DEFAULT 0x57
#define EEPROM_SIZE_BYTES_DEFAULT 4096
#define EEPROM_ADDRESS_BYTES_DEFAULT 2
#define EEPROM_PAGE_SIZE_BYTES_DEFAULT 32
#define EEPROM_WRITE_TIME_MS_DEFAULT 5
#define SYSTEM_I2C_HEALTH_INTERVAL_MS_DEFAULT 2000

// -----------------------------------------------------------------------------
// Keypad UART peripheral
// -----------------------------------------------------------------------------
#define KEYPAD_UART_BAUD_DEFAULT 115200
#define KEYPAD_PROTOCOL_VERSION_DEFAULT 0x03
#define KEYPAD_DEVICE_ID_DEFAULT 0x42
#define KEYPAD_UART_TIMEOUT_MS_DEFAULT 20
#define KEYPAD_RESET_PULSE_MS_DEFAULT 20
#define KEYPAD_BOOT_DELAY_MS_DEFAULT 200

// -----------------------------------------------------------------------------
// Local controls
// -----------------------------------------------------------------------------
#define ENCODER_BUTTON_DEBOUNCE_US_DEFAULT 35000
#define ENCODER_POSITION_DIVIDER_DEFAULT 2
#define CONFIG_RESET_KEY_HOLD_MS_DEFAULT 3000

// -----------------------------------------------------------------------------
// NeoPixel notifications
// -----------------------------------------------------------------------------
#define NOTIFICATION_PIXEL_BRIGHTNESS_DEFAULT 32
#define NOTIFICATION_MODE_DEFAULT 0
#define NOTIFICATION_MODE_COUNT_DEFAULT 4
#define NOTIFICATION_SYSTEM_BUS_PIXEL_DEFAULT 0
#define NOTIFICATION_KEYPAD_BUTTON_PIXEL_DEFAULT 1
#define NOTIFICATION_KEYPAD_BUTTON_RED_DEFAULT 0x34
#define NOTIFICATION_KEYPAD_BUTTON_GREEN_DEFAULT 0x7A
#define NOTIFICATION_KEYPAD_BUTTON_BLUE_DEFAULT 0xEB

// -----------------------------------------------------------------------------
// System status and monitoring
// -----------------------------------------------------------------------------
#define STATUS_LED_BLINK_INTERVAL_MS_DEFAULT 500
#define TEMPERATURE_UNIT_DEFAULT 0
#define HARDWARE_TASK_HEARTBEAT_MS_DEFAULT 1000
#define MCU_MONITOR_INTERVAL_MS_DEFAULT 1000
